#- name : Install Nginx
#  ansible.builtin.dnf:
#    name: nginx
#    state: latest
#
#- name: Start Nginx
#  ansible.builtin.systemd:
#    name: nginx
#    state: restarted
#    enabled: yes

- name: Print variable
  ansible.builtin.debug:
    msg: URL = {{ URL }}

- name: Print variable - task variable defined
  ansible.builtin.debug:
    msg: URL = {{ URL }}
  vars:
    URL: tasks.google.com
