- name: Access Variable
  hosts: localhost
  connection: local
  become: true
  vars:
    URL: play.google.com
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: URL = {{URL}}

### Access the variable using flower braces
    - name: Print Task Level Variable
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: tasks.google.com