- name: Conditions
  hosts: localhost
  connection: local
  become: true
  vars:
    fruit: apple
    vegetable: carrot
  tasks:
    - name: Access Fruits
      ansible.builtin.debug:
        msg: Fruit Name - {{fruit}}
      when: fruit is defined

    - name: Access Vegetables
      ansible.builtin.debug:
        msg: Vegetable - {{vegetable}}
      when: vegetable is defined