- name: Demo On Loops
  hosts: localhost
  connection: local

  vars:
    fruits:
      - kiwi
      - banana


  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: Fruit Name - {{item}}
      loops: "{{fruits}}"

    - name: Print task level Variable
      ansible.builtin.debug:
        msg: Fruit Name - {{item}}
      loops:
        - mango
        - banana

    - name: Print Fruit Names and Quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{item.name}}, Quantity - {{item.quantity}}
      loops: "{{fruits}}"