- name: Demo On Loops
  hosts: localhost
  connection: local

  vars:
    fruits:
      - kiwi
      - banana
  tasks:
    - name: Variable
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop: "{{fruits}}"

    - name:  Local Variables
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop:
        - orange
        - apple

    - name: Variable fruit and quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - { name: "apple", quantity: 200 }
        - { name: "banana", quantity: 100 }
