- name: Demo On Loops
  hosts: localhost
  connection: local

  vars:
    fruits:
      - kiwi
      - banana
  tasks:
    - name: Variable
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop: "{{fruits}}"
