- name: Demo On Templates
  hosts: localhost
  connection: local

  vars:
    fruit_name: apple
  tasks:

    - name: Copied template file
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt
