- name: Demo for AWS Parameter
  hosts: localhost
  connection: local
  tasks:
    - name: lookup ssm parameter store
      debug: msg="{{ lookup('aws_ssm', 'rds.dev.database_name', region='us-east-1' ) }}"